### PR TITLE
update folder structure for git workflows

### PR DESCRIPTION
**Pull request by aadyr**
changes to workflows directory structure

### CODE REVIEW

**Comment by ioctlsg** [comment]
all is good. adding workflow folder

**Comment by ioctlsg** [comment]
all is good

**Comment by ioctlsg** [comment]
all is good

**Review by ioctlsg — COMMENTED** [review]
all is good

**Comment by vincent8055** [comment]
reopen

**Review by vincent8055 — APPROVED** [review]

**Review by vincent8055 — APPROVED** [review]
approved

**Pull request merged**
